In [2]:
import cv2
import time


In [ ]:
#Give the path to video file or numbers will be using the webcam to capture video
video=cv2.VideoCapture(0) #0-Built in camera,1-one webcam 2-two webcam
a=1
while True:
    a=a+1
    
    check,frame=video.read()#Read the first frame/image of the video
#check is a boolean data type and it returns true if python is able to read the video capture object
#frame is a numpy array,it represents the first image that video captures
    print(check)
    print(frame)
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('CaptureVideo',gray)
    key = cv2.waitKey(1)
    if key==ord('q'):
         break
print(a)
#video.release()
cv2.destroyAllWindows()


True
[[[123 112  92]
  [121 110  90]
  [115 112  90]
  ...
  [204 179 154]
  [206 181 161]
  [204 179 159]]

 [[121 113  92]
  [119 111  90]
  [117 113  93]
  ...
  [204 178 155]
  [208 182 159]
  [206 180 157]]

 [[121 113  92]
  [122 114  93]
  [118 114  94]
  ...
  [204 179 154]
  [208 180 156]
  [208 180 156]]

 ...

 [[114 105  86]
  [114 105  86]
  [116 103  88]
  ...
  [155 134 117]
  [153 134 117]
  [154 135 118]]

 [[113 102  82]
  [116 105  85]
  [117 105  87]
  ...
  [155 131 115]
  [154 133 116]
  [155 134 117]]

 [[114 103  81]
  [117 106  84]
  [117 106  86]
  ...
  [154 127 114]
  [155 131 115]
  [157 133 117]]]
True
[[[117 109 101]
  [118 110 102]
  [124 110  97]
  ...
  [211 181 150]
  [208 181 149]
  [208 181 149]]

 [[122 111 104]
  [121 110 103]
  [124 109  99]
  ...
  [211 181 150]
  [209 182 150]
  [209 182 150]]

 [[126 115 108]
  [121 110 103]
  [121 106  96]
  ...
  [211 180 152]
  [209 181 152]
  [209 181 152]]

 ...

 [[114 105  86]
  [115 106  87]
  [116 106

True
[[[142 146 147]
  [141 145 146]
  [152 140 150]
  ...
  [239 227 209]
  [242 227 207]
  [243 228 208]]

 [[145 147 147]
  [144 146 146]
  [150 140 150]
  ...
  [242 226 213]
  [244 229 209]
  [243 228 208]]

 [[151 151 151]
  [146 146 146]
  [150 141 148]
  ...
  [248 225 213]
  [244 226 207]
  [247 229 210]]

 ...

 [[139 139 128]
  [139 139 128]
  [140 139 130]
  ...
  [187 172 162]
  [183 173 162]
  [181 171 160]]

 [[137 136 127]
  [137 136 127]
  [135 136 127]
  ...
  [185 170 160]
  [181 171 160]
  [180 170 159]]

 [[137 136 127]
  [137 136 127]
  [134 135 126]
  ...
  [183 168 158]
  [181 169 158]
  [182 170 159]]]
True
[[[151 146 141]
  [152 147 142]
  [150 146 146]
  ...
  [255 226 215]
  [255 224 216]
  [255 227 219]]

 [[152 147 142]
  [153 148 143]
  [150 146 146]
  ...
  [255 224 216]
  [255 224 216]
  [255 225 217]]

 [[151 145 142]
  [154 148 145]
  [150 146 147]
  ...
  [254 223 215]
  [255 224 216]
  [255 225 217]]

 ...

 [[137 137 131]
  [134 134 128]
  [138 134

True
[[[149 148 144]
  [146 145 141]
  [142 145 141]
  ...
  [240 227 212]
  [233 227 212]
  [233 227 212]]

 [[147 148 144]
  [145 146 142]
  [144 144 143]
  ...
  [240 226 213]
  [237 227 216]
  [233 223 212]]

 [[150 149 145]
  [148 147 143]
  [144 144 143]
  ...
  [241 227 214]
  [239 227 216]
  [238 226 215]]

 ...

 [[132 132 132]
  [133 133 133]
  [135 133 134]
  ...
  [179 169 166]
  [177 168 168]
  [180 171 171]]

 [[131 131 130]
  [133 133 132]
  [134 132 133]
  ...
  [179 169 166]
  [177 170 170]
  [178 171 171]]

 [[131 131 130]
  [132 132 131]
  [134 132 133]
  ...
  [179 171 168]
  [177 168 168]
  [176 167 167]]]
True
[[[157 141 149]
  [155 139 147]
  [158 142 143]
  ...
  [250 223 215]
  [251 222 214]
  [251 222 214]]

 [[155 140 146]
  [154 139 145]
  [160 141 143]
  ...
  [251 222 216]
  [251 222 214]
  [251 222 214]]

 [[151 136 142]
  [152 137 143]
  [157 141 142]
  ...
  [251 222 216]
  [250 221 213]
  [253 224 216]]

 ...

 [[138 131 133]
  [138 131 133]
  [136 132

True
[[[145 138 159]
  [145 138 159]
  [140 139 155]
  ...
  [233 223 220]
  [234 222 218]
  [235 223 219]]

 [[146 140 158]
  [147 141 159]
  [142 139 155]
  ...
  [236 224 220]
  [236 227 222]
  [236 227 222]]

 [[145 143 156]
  [145 143 156]
  [143 140 156]
  ...
  [237 226 219]
  [236 227 222]
  [236 227 222]]

 ...

 [[134 132 131]
  [134 132 131]
  [131 133 134]
  ...
  [181 174 175]
  [178 175 179]
  [171 168 172]]

 [[132 132 131]
  [133 133 132]
  [131 133 133]
  ...
  [177 170 172]
  [174 172 178]
  [174 172 178]]

 [[132 132 131]
  [132 132 131]
  [130 132 131]
  ...
  [177 170 172]
  [171 170 174]
  [172 171 175]]]
True
[[[149 145 145]
  [151 147 147]
  [150 146 146]
  ...
  [236 222 223]
  [238 219 222]
  [239 220 223]]

 [[150 146 146]
  [151 147 147]
  [152 145 146]
  ...
  [236 222 224]
  [236 220 222]
  [238 222 224]]

 [[148 146 145]
  [148 146 145]
  [151 145 142]
  ...
  [237 221 223]
  [236 220 223]
  [236 220 223]]

 ...

 [[136 129 138]
  [137 130 139]
  [141 135

True
[[[137 146 151]
  [137 146 151]
  [137 145 153]
  ...
  [226 227 223]
  [232 225 227]
  [231 224 226]]

 [[137 145 153]
  [137 145 153]
  [137 146 151]
  ...
  [228 226 225]
  [232 225 226]
  [230 223 224]]

 [[138 147 152]
  [137 146 151]
  [138 145 150]
  ...
  [228 226 226]
  [232 225 226]
  [229 222 223]]

 ...

 [[134 134 140]
  [134 134 140]
  [135 136 140]
  ...
  [175 171 171]
  [174 172 172]
  [174 172 172]]

 [[134 134 140]
  [134 134 140]
  [135 136 140]
  ...
  [173 169 169]
  [171 169 170]
  [174 172 173]]

 [[133 132 141]
  [133 132 141]
  [133 134 138]
  ...
  [174 167 169]
  [170 166 172]
  [174 170 176]]]
True
[[[143 147 148]
  [143 147 148]
  [148 148 137]
  ...
  [240 222 221]
  [240 223 220]
  [240 223 220]]

 [[145 147 148]
  [145 147 148]
  [150 148 142]
  ...
  [240 220 219]
  [236 222 218]
  [238 224 220]]

 [[145 145 146]
  [143 143 144]
  [150 144 141]
  ...
  [233 218 216]
  [230 218 214]
  [235 223 219]]

 ...

 [[129 131 137]
  [131 133 139]
  [131 134

True
[[[135 149 146]
  [133 147 144]
  [139 142 146]
  ...
  [240 225 215]
  [238 231 219]
  [235 228 216]]

 [[138 149 148]
  [136 147 146]
  [139 142 146]
  ...
  [239 226 219]
  [236 227 222]
  [235 226 221]]

 [[136 147 147]
  [135 146 146]
  [140 143 147]
  ...
  [235 226 221]
  [234 226 223]
  [234 226 223]]

 ...

 [[125 130 135]
  [125 130 135]
  [122 131 136]
  ...
  [171 167 173]
  [173 171 172]
  [174 172 173]]

 [[124 131 136]
  [123 130 135]
  [122 131 136]
  ...
  [173 167 173]
  [173 171 172]
  [174 172 173]]

 [[125 132 137]
  [124 131 136]
  [124 131 136]
  ...
  [173 167 173]
  [171 169 169]
  [175 173 173]]]
True
[[[139 141 156]
  [138 140 155]
  [143 139 152]
  ...
  [231 224 225]
  [233 222 223]
  [233 222 223]]

 [[139 141 156]
  [139 141 156]
  [143 141 152]
  ...
  [231 224 225]
  [236 225 227]
  [234 223 225]]

 [[141 145 153]
  [140 144 152]
  [144 143 152]
  ...
  [234 225 227]
  [236 225 227]
  [234 223 225]]

 ...

 [[131 130 139]
  [131 130 139]
  [133 131

True
[[[146 144 150]
  [145 143 149]
  [146 140 151]
  ...
  [228 221 223]
  [229 218 225]
  [230 219 226]]

 [[145 143 149]
  [144 142 148]
  [139 136 145]
  ...
  [230 221 222]
  [230 220 225]
  [231 221 226]]

 [[145 143 149]
  [144 142 148]
  [142 138 144]
  ...
  [229 222 223]
  [231 221 226]
  [233 223 228]]

 ...

 [[131 131 142]
  [131 131 142]
  [135 132 141]
  ...
  [171 170 174]
  [167 169 170]
  [166 168 169]]

 [[133 134 143]
  [131 132 141]
  [135 132 141]
  ...
  [172 170 176]
  [167 168 172]
  [165 166 170]]

 [[133 134 143]
  [131 132 141]
  [135 132 141]
  ...
  [165 165 171]
  [165 165 171]
  [165 165 171]]]
True
[[[146 146 147]
  [142 142 143]
  [146 135 142]
  ...
  [238 226 231]
  [239 222 228]
  [237 220 226]]

 [[147 147 148]
  [143 143 144]
  [145 136 143]
  ...
  [242 225 231]
  [239 222 228]
  [238 221 227]]

 [[150 149 153]
  [144 143 147]
  [143 136 145]
  ...
  [238 221 227]
  [237 222 228]
  [237 222 228]]

 ...

 [[128 129 138]
  [129 130 139]
  [129 134

True
[[[130 148 149]
  [130 148 149]
  [135 143 146]
  ...
  [237 221 224]
  [237 221 223]
  [237 221 223]]

 [[132 147 149]
  [133 148 150]
  [145 152 157]
  ...
  [238 222 223]
  [239 223 225]
  [239 223 225]]

 [[131 146 148]
  [121 136 138]
  [117 129 133]
  ...
  [238 223 221]
  [239 223 224]
  [240 224 225]]

 ...

 [[127 134 133]
  [126 133 132]
  [128 132 131]
  ...
  [177 170 171]
  [175 171 172]
  [173 169 170]]

 [[125 134 134]
  [124 133 133]
  [130 132 131]
  ...
  [176 172 172]
  [174 171 175]
  [171 168 172]]

 [[125 135 138]
  [123 133 136]
  [131 133 133]
  ...
  [174 172 172]
  [174 171 175]
  [173 170 174]]]
True
[[[141 146 151]
  [140 145 150]
  [144 140 158]
  ...
  [227 224 220]
  [235 226 212]
  [236 227 213]]

 [[142 146 154]
  [142 146 154]
  [144 141 157]
  ...
  [230 223 223]
  [233 226 214]
  [235 228 216]]

 [[137 145 153]
  [136 144 152]
  [140 140 153]
  ...
  [235 224 226]
  [238 226 217]
  [237 225 216]]

 ...

 [[131 131 137]
  [133 133 139]
  [129 132

True
[[[146 148 149]
  [148 150 151]
  [155 147 144]
  ...
  [243 221 228]
  [245 222 226]
  [243 220 224]]

 [[146 148 148]
  [146 148 148]
  [154 147 148]
  ...
  [243 221 228]
  [243 222 226]
  [242 221 225]]

 [[145 147 148]
  [145 147 148]
  [150 146 147]
  ...
  [242 221 224]
  [238 222 225]
  [239 223 226]]

 ...

 [[133 134 138]
  [134 135 139]
  [129 135 138]
  ...
  [171 168 172]
  [169 169 170]
  [172 172 173]]

 [[131 132 136]
  [133 134 138]
  [125 134 139]
  ...
  [172 167 171]
  [171 169 169]
  [173 171 171]]

 [[132 130 136]
  [133 131 137]
  [126 131 136]
  ...
  [172 167 171]
  [170 168 168]
  [171 169 169]]]
True
[[[140 145 155]
  [138 143 153]
  [142 147 152]
  ...
  [232 221 228]
  [237 220 231]
  [237 220 231]]

 [[141 145 153]
  [139 143 151]
  [138 145 150]
  ...
  [234 226 231]
  [236 222 232]
  [232 218 228]]

 [[149 150 159]
  [142 143 152]
  [143 145 146]
  ...
  [233 228 232]
  [236 222 232]
  [225 211 221]]

 ...

 [[135 134 138]
  [137 136 140]
  [136 136

True
[[[145 143 154]
  [145 143 154]
  [145 142 151]
  ...
  [226 224 224]
  [230 225 220]
  [228 223 218]]

 [[143 141 152]
  [143 141 152]
  [145 142 151]
  ...
  [226 224 224]
  [229 223 220]
  [229 223 220]]

 [[142 140 151]
  [143 141 152]
  [145 142 151]
  ...
  [227 223 222]
  [231 223 220]
  [231 223 220]]

 ...

 [[131 133 139]
  [128 130 136]
  [127 131 139]
  ...
  [171 167 166]
  [169 167 167]
  [171 169 169]]

 [[132 134 140]
  [129 131 137]
  [127 131 139]
  ...
  [171 167 166]
  [169 167 167]
  [171 169 169]]

 [[131 136 141]
  [129 134 139]
  [127 132 137]
  ...
  [171 167 166]
  [169 167 167]
  [171 169 169]]]
True
[[[139 145 148]
  [140 146 149]
  [139 148 147]
  ...
  [234 220 223]
  [228 221 222]
  [230 223 224]]

 [[139 146 146]
  [139 146 146]
  [141 148 148]
  ...
  [235 221 223]
  [237 224 217]
  [238 225 218]]

 [[138 145 145]
  [139 146 146]
  [140 147 146]
  ...
  [237 223 219]
  [238 223 215]
  [240 225 217]]

 ...

 [[133 135 135]
  [133 135 135]
  [128 132

True
[[[134 154 155]
  [132 152 153]
  [132 147 149]
  ...
  [240 222 221]
  [238 224 225]
  [238 224 225]]

 [[132 150 151]
  [132 150 151]
  [132 147 149]
  ...
  [240 221 223]
  [239 223 225]
  [240 224 226]]

 [[131 149 150]
  [130 148 149]
  [134 147 149]
  ...
  [239 223 226]
  [237 223 226]
  [240 226 229]]

 ...

 [[129 134 139]
  [129 134 139]
  [125 133 136]
  ...
  [168 167 171]
  [166 168 169]
  [166 168 169]]

 [[127 133 136]
  [126 132 135]
  [124 132 135]
  ...
  [167 167 168]
  [166 166 166]
  [166 166 166]]

 [[126 132 135]
  [126 132 135]
  [126 132 135]
  ...
  [168 166 167]
  [170 167 163]
  [171 168 164]]]
True
[[[139 144 154]
  [138 143 153]
  [130 149 147]
  ...
  [231 224 219]
  [235 221 224]
  [236 222 225]]

 [[138 143 153]
  [138 143 153]
  [131 146 148]
  ...
  [233 223 220]
  [235 221 223]
  [237 223 225]]

 [[137 142 152]
  [136 141 151]
  [132 145 147]
  ...
  [232 222 219]
  [235 221 223]
  [237 223 225]]

 ...

 [[129 136 136]
  [129 136 136]
  [133 132

True
[[[146 148 142]
  [146 148 142]
  [137 148 141]
  ...
  [234 226 231]
  [231 226 235]
  [228 223 232]]

 [[144 147 143]
  [144 147 143]
  [137 147 142]
  ...
  [231 224 226]
  [232 226 232]
  [232 226 232]]

 [[142 147 143]
  [142 147 143]
  [137 146 144]
  ...
  [230 223 225]
  [229 224 228]
  [232 227 231]]

 ...

 [[132 128 141]
  [135 131 144]
  [136 135 144]
  ...
  [173 169 168]
  [173 173 173]
  [171 171 171]]

 [[136 132 143]
  [137 133 144]
  [139 137 143]
  ...
  [175 171 170]
  [174 174 174]
  [174 174 174]]

 [[136 132 143]
  [137 133 144]
  [137 136 140]
  ...
  [177 168 168]
  [174 172 172]
  [174 172 172]]]
True
[[[148 148 149]
  [147 147 148]
  [144 140 153]
  ...
  [234 225 227]
  [234 225 226]
  [232 223 224]]

 [[148 145 149]
  [148 145 149]
  [144 140 151]
  ...
  [233 224 226]
  [231 224 224]
  [229 222 222]]

 [[145 144 148]
  [145 144 148]
  [142 141 150]
  ...
  [231 222 224]
  [232 225 225]
  [232 225 225]]

 ...

 [[137 139 140]
  [131 133 134]
  [127 134

True
[[[139 143 144]
  [142 146 147]
  [140 147 152]
  ...
  [238 227 227]
  [240 223 229]
  [239 222 228]]

 [[139 143 144]
  [141 145 146]
  [138 145 150]
  ...
  [240 227 225]
  [238 224 227]
  [237 223 226]]

 [[137 143 146]
  [139 145 148]
  [138 145 150]
  ...
  [240 230 221]
  [238 224 225]
  [236 222 223]]

 ...

 [[131 132 141]
  [131 132 141]
  [127 132 142]
  ...
  [170 170 176]
  [173 171 177]
  [169 167 173]]

 [[128 133 143]
  [127 132 142]
  [126 133 143]
  ...
  [167 169 175]
  [172 170 176]
  [168 166 172]]

 [[128 133 143]
  [127 132 142]
  [128 136 144]
  ...
  [163 168 173]
  [168 166 172]
  [167 165 171]]]
True
[[[149 149 129]
  [150 150 130]
  [148 149 140]
  ...
  [241 227 230]
  [242 227 225]
  [240 225 223]]

 [[149 146 134]
  [150 147 135]
  [148 149 140]
  ...
  [240 224 227]
  [240 224 225]
  [240 224 225]]

 [[144 143 139]
  [146 145 141]
  [147 146 142]
  ...
  [238 222 225]
  [239 223 224]
  [239 223 224]]

 ...

 [[131 131 137]
  [133 133 139]
  [131 132

True
[[[146 143 152]
  [146 143 152]
  [146 143 152]
  ...
  [232 223 224]
  [229 225 224]
  [229 225 224]]

 [[146 144 150]
  [146 144 150]
  [146 143 152]
  ...
  [230 223 224]
  [229 225 225]
  [229 225 225]]

 [[147 145 151]
  [146 144 150]
  [146 143 152]
  ...
  [232 223 224]
  [230 226 227]
  [232 228 229]]

 ...

 [[127 131 139]
  [129 133 141]
  [130 134 142]
  ...
  [170 168 179]
  [169 168 177]
  [169 168 177]]

 [[129 133 141]
  [129 133 141]
  [128 134 142]
  ...
  [169 168 177]
  [169 170 174]
  [169 170 174]]

 [[130 134 142]
  [129 133 141]
  [131 135 143]
  ...
  [171 169 175]
  [169 171 172]
  [170 172 173]]]
True
[[[145 145 151]
  [148 148 154]
  [145 152 151]
  ...
  [237 227 218]
  [232 225 220]
  [232 225 220]]

 [[145 146 150]
  [146 147 151]
  [146 150 151]
  ...
  [237 225 221]
  [232 224 221]
  [231 223 220]]

 [[143 144 148]
  [146 147 151]
  [144 148 149]
  ...
  [235 224 224]
  [233 224 224]
  [234 225 225]]

 ...

 [[128 129 138]
  [129 130 139]
  [134 134

True
[[[153 145 150]
  [151 143 148]
  [150 140 145]
  ...
  [234 219 231]
  [224 222 228]
  [224 222 228]]

 [[154 144 149]
  [153 143 148]
  [151 141 146]
  ...
  [234 220 230]
  [227 223 229]
  [227 223 229]]

 [[153 143 148]
  [152 142 147]
  [149 141 146]
  ...
  [229 219 229]
  [230 223 232]
  [229 222 231]]

 ...

 [[137 134 138]
  [138 135 139]
  [136 135 139]
  ...
  [175 171 172]
  [173 171 171]
  [171 169 169]]

 [[133 132 136]
  [136 135 139]
  [136 135 139]
  ...
  [174 167 168]
  [171 169 169]
  [171 169 169]]

 [[135 134 138]
  [135 134 138]
  [135 136 140]
  ...
  [173 166 168]
  [170 168 169]
  [171 169 170]]]
True
[[[141 141 154]
  [140 140 153]
  [144 144 144]
  ...
  [233 225 236]
  [236 227 234]
  [235 226 233]]

 [[141 141 152]
  [140 140 151]
  [144 144 145]
  ...
  [233 225 236]
  [235 227 232]
  [237 229 234]]

 [[144 142 153]
  [143 141 152]
  [142 139 143]
  ...
  [232 222 232]
  [236 227 228]
  [239 230 231]]

 ...

 [[123 132 137]
  [125 134 139]
  [127 133

True
[[[144 146 145]
  [145 147 146]
  [137 144 144]
  ...
  [239 225 221]
  [241 220 224]
  [244 223 227]]

 [[143 145 145]
  [144 146 146]
  [137 144 143]
  ...
  [240 226 227]
  [239 220 224]
  [242 223 227]]

 [[142 142 142]
  [144 144 144]
  [137 144 143]
  ...
  [242 226 228]
  [238 222 224]
  [237 221 223]]

 ...

 [[134 125 146]
  [134 125 146]
  [135 129 140]
  ...
  [168 171 175]
  [175 173 173]
  [174 172 172]]

 [[133 125 148]
  [135 127 150]
  [135 131 144]
  ...
  [167 170 174]
  [177 173 172]
  [177 173 172]]

 [[135 127 150]
  [136 128 151]
  [137 133 146]
  ...
  [167 168 172]
  [171 167 168]
  [171 167 168]]]
True
[[[133 143 152]
  [134 144 153]
  [143 141 147]
  ...
  [224 222 223]
  [226 221 225]
  [225 220 224]]

 [[135 142 152]
  [136 143 153]
  [142 142 148]
  ...
  [226 222 223]
  [226 221 225]
  [226 221 225]]

 [[138 143 153]
  [138 143 153]
  [140 141 150]
  ...
  [225 221 222]
  [229 220 220]
  [231 222 222]]

 ...

 [[129 135 138]
  [130 136 139]
  [130 136

True
[[[146 148 137]
  [147 149 138]
  [149 149 138]
  ...
  [243 225 219]
  [243 224 221]
  [241 222 219]]

 [[145 146 137]
  [147 148 139]
  [147 147 141]
  ...
  [243 224 221]
  [241 223 222]
  [239 221 220]]

 [[143 144 140]
  [145 146 142]
  [147 145 144]
  ...
  [241 224 221]
  [241 223 222]
  [240 222 221]]

 ...

 [[128 132 133]
  [132 136 137]
  [129 136 134]
  ...
  [168 172 173]
  [171 173 173]
  [170 172 172]]

 [[126 133 133]
  [129 136 136]
  [123 134 133]
  ...
  [165 169 170]
  [170 172 172]
  [171 173 173]]

 [[122 132 135]
  [125 135 138]
  [123 134 133]
  ...
  [163 166 170]
  [172 168 168]
  [171 167 167]]]
True
[[[138 140 160]
  [140 142 162]
  [137 143 158]
  ...
  [235 222 220]
  [233 223 220]
  [233 223 220]]

 [[139 141 161]
  [142 144 164]
  [136 142 157]
  ...
  [234 220 221]
  [234 223 224]
  [234 223 224]]

 [[139 142 159]
  [135 138 155]
  [131 140 154]
  ...
  [238 227 228]
  [235 226 221]
  [235 226 221]]

 ...

 [[125 133 141]
  [126 134 142]
  [127 133

True
[[[143 145 151]
  [144 146 152]
  [146 144 155]
  ...
  [241 225 219]
  [239 231 223]
  [240 232 224]]

 [[143 145 151]
  [143 145 151]
  [144 142 153]
  ...
  [240 228 219]
  [239 231 223]
  [239 231 223]]

 [[143 145 151]
  [142 144 150]
  [143 141 152]
  ...
  [245 230 222]
  [242 230 221]
  [237 225 216]]

 ...

 [[135 131 130]
  [133 129 128]
  [134 131 127]
  ...
  [172 172 178]
  [170 170 176]
  [169 169 175]]

 [[136 129 130]
  [136 129 130]
  [134 130 129]
  ...
  [170 170 176]
  [171 171 177]
  [169 169 175]]

 [[136 129 131]
  [137 130 132]
  [135 131 132]
  ...
  [171 169 175]
  [170 170 176]
  [170 170 176]]]
True
[[[135 147 142]
  [132 144 139]
  [130 146 129]
  ...
  [236 223 221]
  [233 222 222]
  [233 222 222]]

 [[137 148 141]
  [135 146 139]
  [135 148 134]
  ...
  [236 223 221]
  [233 223 220]
  [232 222 219]]

 [[137 147 142]
  [136 146 141]
  [135 148 134]
  ...
  [237 223 224]
  [234 224 221]
  [232 222 219]]

 ...

 [[130 132 133]
  [130 132 133]
  [131 133

True
[[[150 148 148]
  [148 146 146]
  [149 138 150]
  ...
  [234 225 227]
  [241 227 230]
  [238 224 227]]

 [[149 147 148]
  [148 146 147]
  [147 140 149]
  ...
  [234 224 229]
  [236 224 229]
  [236 224 229]]

 [[146 143 147]
  [146 143 147]
  [147 141 147]
  ...
  [234 224 229]
  [238 224 234]
  [236 222 232]]

 ...

 [[126 130 130]
  [127 131 131]
  [125 132 137]
  ...
  [174 165 172]
  [177 169 174]
  [178 170 175]]

 [[125 130 135]
  [126 131 136]
  [127 133 141]
  ...
  [173 166 175]
  [173 170 174]
  [171 168 172]]

 [[126 131 136]
  [127 132 137]
  [128 134 142]
  ...
  [172 169 178]
  [173 170 174]
  [171 168 172]]]
True
[[[142 144 138]
  [140 142 136]
  [141 143 142]
  ...
  [235 219 220]
  [240 223 220]
  [241 224 221]]

 [[141 144 140]
  [141 144 140]
  [139 143 142]
  ...
  [234 220 222]
  [239 224 222]
  [238 223 221]]

 [[142 145 141]
  [141 144 140]
  [139 143 142]
  ...
  [235 224 226]
  [239 224 222]
  [236 221 219]]

 ...

 [[133 135 136]
  [133 135 136]
  [134 132

True
[[[139 142 154]
  [140 143 155]
  [140 143 153]
  ...
  [238 223 221]
  [232 223 225]
  [232 223 225]]

 [[139 142 152]
  [139 142 152]
  [140 143 153]
  ...
  [237 224 222]
  [235 224 225]
  [235 224 225]]

 [[139 142 152]
  [138 141 151]
  [139 143 151]
  ...
  [239 228 228]
  [234 225 225]
  [232 223 223]]

 ...

 [[129 133 133]
  [129 133 133]
  [131 134 138]
  ...
  [171 168 172]
  [173 168 172]
  [175 170 174]]

 [[129 133 133]
  [129 133 133]
  [131 135 136]
  ...
  [175 170 174]
  [176 171 175]
  [176 171 175]]

 [[129 133 133]
  [129 133 133]
  [132 136 137]
  ...
  [173 167 173]
  [176 171 175]
  [176 171 175]]]
True
[[[147 139 164]
  [147 139 164]
  [153 138 162]
  ...
  [238 223 221]
  [239 219 226]
  [242 222 229]]

 [[149 139 162]
  [149 139 162]
  [151 140 161]
  ...
  [238 223 221]
  [236 220 223]
  [238 222 225]]

 [[150 141 162]
  [149 140 161]
  [150 141 157]
  ...
  [238 224 226]
  [236 225 227]
  [235 224 226]]

 ...

 [[128 128 141]
  [132 132 145]
  [131 132

True
[[[142 144 145]
  [142 144 145]
  [146 142 148]
  ...
  [238 223 221]
  [240 227 220]
  [238 225 218]]

 [[142 143 147]
  [142 143 147]
  [146 142 148]
  ...
  [238 224 220]
  [236 224 220]
  [236 224 220]]

 [[140 143 147]
  [138 141 145]
  [146 142 148]
  ...
  [237 224 222]
  [235 224 225]
  [238 227 228]]

 ...

 [[131 135 135]
  [129 133 133]
  [131 135 135]
  ...
  [169 167 167]
  [175 171 170]
  [175 171 170]]

 [[130 132 131]
  [130 132 131]
  [131 133 133]
  ...
  [170 166 165]
  [175 169 166]
  [174 168 165]]

 [[129 131 130]
  [130 132 131]
  [130 132 132]
  ...
  [170 166 165]
  [176 170 162]
  [176 170 162]]]
True
[[[142 149 154]
  [139 146 151]
  [147 141 154]
  ...
  [237 227 232]
  [227 228 232]
  [223 224 228]]

 [[141 150 155]
  [138 147 152]
  [147 141 152]
  ...
  [238 228 233]
  [229 227 233]
  [223 221 227]]

 [[142 149 154]
  [139 146 151]
  [148 143 152]
  ...
  [240 229 229]
  [230 227 231]
  [224 221 225]]

 ...

 [[124 138 142]
  [121 135 139]
  [121 134

True
[[[144 147 151]
  [143 146 150]
  [146 142 153]
  ...
  [231 224 225]
  [225 226 222]
  [223 224 220]]

 [[144 147 151]
  [143 146 150]
  [144 142 153]
  ...
  [229 225 226]
  [229 226 222]
  [228 225 221]]

 [[144 146 152]
  [144 146 152]
  [145 144 153]
  ...
  [229 222 223]
  [230 224 221]
  [230 224 221]]

 ...

 [[133 135 135]
  [134 136 136]
  [133 135 136]
  ...
  [171 171 172]
  [171 170 174]
  [172 171 175]]

 [[133 135 135]
  [133 135 135]
  [131 133 133]
  ...
  [172 172 173]
  [171 170 174]
  [172 171 175]]

 [[133 135 135]
  [133 135 135]
  [133 135 135]
  ...
  [170 171 175]
  [169 170 174]
  [170 171 175]]]
True
[[[134 144 153]
  [135 145 154]
  [136 146 155]
  ...
  [235 224 224]
  [237 225 221]
  [238 226 222]]

 [[134 144 153]
  [135 145 154]
  [135 145 154]
  ...
  [234 224 221]
  [241 229 225]
  [236 224 220]]

 [[135 145 154]
  [134 144 153]
  [131 143 154]
  ...
  [230 226 225]
  [236 227 222]
  [234 225 220]]

 ...

 [[125 129 137]
  [125 129 137]
  [124 129

True
[[[135 142 152]
  [135 142 152]
  [144 135 156]
  ...
  [232 223 218]
  [236 220 221]
  [235 219 220]]

 [[137 142 154]
  [137 142 154]
  [145 137 155]
  ...
  [235 223 219]
  [236 220 222]
  [236 220 222]]

 [[137 140 150]
  [139 142 152]
  [147 140 156]
  ...
  [236 225 218]
  [235 221 223]
  [236 222 224]]

 ...

 [[129 134 139]
  [129 134 139]
  [130 135 140]
  ...
  [169 166 170]
  [170 165 174]
  [171 166 175]]

 [[129 134 139]
  [129 134 139]
  [129 134 139]
  ...
  [173 168 172]
  [171 167 173]
  [171 167 173]]

 [[129 134 139]
  [129 134 139]
  [130 135 140]
  ...
  [174 171 175]
  [173 169 175]
  [171 167 173]]]
True
[[[143 141 159]
  [147 145 163]
  [144 150 158]
  ...
  [236 225 218]
  [240 227 220]
  [239 226 219]]

 [[144 141 157]
  [146 143 159]
  [142 147 152]
  ...
  [236 225 218]
  [238 224 220]
  [239 225 221]]

 [[142 140 158]
  [139 137 155]
  [139 143 151]
  ...
  [230 223 218]
  [233 223 220]
  [234 224 221]]

 ...

 [[136 129 138]
  [139 132 141]
  [139 133

True
[[[149 147 148]
  [150 148 149]
  [149 143 156]
  ...
  [225 225 226]
  [227 222 231]
  [226 221 230]]

 [[147 146 150]
  [150 149 153]
  [150 144 155]
  ...
  [227 225 226]
  [226 221 230]
  [226 221 230]]

 [[145 145 151]
  [145 145 151]
  [149 143 154]
  ...
  [229 222 222]
  [228 223 227]
  [229 224 228]]

 ...

 [[131 132 136]
  [131 132 136]
  [131 130 139]
  ...
  [170 168 167]
  [168 168 169]
  [169 169 170]]

 [[132 131 135]
  [135 134 138]
  [136 134 140]
  ...
  [169 167 167]
  [167 167 168]
  [168 168 169]]

 [[132 131 135]
  [135 134 138]
  [136 134 140]
  ...
  [170 166 166]
  [167 166 170]
  [169 168 172]]]
True
[[[149 141 152]
  [149 141 152]
  [146 139 155]
  ...
  [226 222 228]
  [233 223 228]
  [232 222 227]]

 [[146 140 151]
  [147 141 152]
  [147 139 157]
  ...
  [229 224 228]
  [232 222 227]
  [232 222 227]]

 [[146 140 151]
  [147 141 152]
  [145 139 157]
  ...
  [232 225 225]
  [234 223 224]
  [235 224 225]]

 ...

 [[133 133 133]
  [132 132 132]
  [130 132

True
[[[136 139 143]
  [139 142 146]
  [140 140 146]
  ...
  [236 222 223]
  [240 221 223]
  [241 222 224]]

 [[141 142 146]
  [142 143 147]
  [140 143 147]
  ...
  [237 224 222]
  [240 224 226]
  [239 223 225]]

 [[142 145 149]
  [141 144 148]
  [140 143 147]
  ...
  [238 225 223]
  [240 226 228]
  [237 223 225]]

 ...

 [[133 132 141]
  [133 132 141]
  [131 131 137]
  ...
  [171 167 173]
  [170 166 172]
  [171 167 173]]

 [[133 132 141]
  [133 132 141]
  [133 133 139]
  ...
  [178 173 177]
  [175 169 175]
  [175 169 175]]

 [[129 128 137]
  [131 130 139]
  [133 133 139]
  ...
  [177 173 174]
  [175 169 175]
  [175 169 175]]]
True
[[[149 142 151]
  [146 139 148]
  [144 144 144]
  ...
  [229 226 222]
  [228 227 223]
  [230 229 225]]

 [[145 143 149]
  [144 142 148]
  [146 148 149]
  ...
  [229 226 222]
  [227 226 222]
  [228 227 223]]

 [[145 144 148]
  [146 145 149]
  [148 150 151]
  ...
  [234 225 225]
  [232 227 222]
  [232 227 222]]

 ...

 [[130 129 138]
  [131 130 139]
  [131 129

True
[[[144 144 150]
  [143 143 149]
  [140 139 155]
  ...
  [231 222 229]
  [233 223 228]
  [232 222 227]]

 [[144 143 152]
  [143 142 151]
  [140 139 155]
  ...
  [234 223 230]
  [233 224 226]
  [231 222 224]]

 [[144 143 152]
  [143 142 151]
  [141 140 156]
  ...
  [236 227 229]
  [233 224 226]
  [232 223 225]]

 ...

 [[132 129 138]
  [135 132 141]
  [135 135 141]
  ...
  [173 168 172]
  [173 169 175]
  [173 169 175]]

 [[136 133 142]
  [136 133 142]
  [132 134 140]
  ...
  [173 168 172]
  [173 169 175]
  [174 170 176]]

 [[136 133 142]
  [136 133 142]
  [133 133 139]
  ...
  [172 166 172]
  [170 166 172]
  [171 167 173]]]
True
[[[148 142 155]
  [149 143 156]
  [146 140 158]
  ...
  [239 221 220]
  [241 222 219]
  [242 223 220]]

 [[148 142 155]
  [149 143 156]
  [148 141 157]
  ...
  [241 228 226]
  [240 223 220]
  [239 222 219]]

 [[148 142 155]
  [148 142 155]
  [147 142 158]
  ...
  [239 230 225]
  [238 224 220]
  [239 225 221]]

 ...

 [[137 136 140]
  [137 136 140]
  [136 135

True
[[[142 145 149]
  [140 143 147]
  [149 138 150]
  ...
  [235 221 224]
  [231 219 224]
  [233 221 226]]

 [[142 144 150]
  [140 142 148]
  [145 139 150]
  ...
  [237 223 225]
  [233 219 221]
  [234 220 222]]

 [[141 143 149]
  [139 141 147]
  [145 139 150]
  ...
  [236 225 225]
  [239 225 221]
  [236 222 218]]

 ...

 [[130 134 142]
  [131 135 143]
  [127 133 141]
  ...
  [169 168 177]
  [170 168 179]
  [169 167 178]]

 [[129 133 141]
  [131 135 143]
  [129 134 139]
  ...
  [167 165 176]
  [168 168 181]
  [168 168 181]]

 [[131 132 141]
  [132 133 142]
  [129 134 139]
  ...
  [171 165 176]
  [167 165 176]
  [167 165 176]]]
True
[[[145 148 139]
  [144 147 138]
  [146 144 145]
  ...
  [238 225 223]
  [237 224 222]
  [240 227 225]]

 [[145 147 141]
  [145 147 141]
  [145 145 145]
  ...
  [238 225 223]
  [237 223 224]
  [238 224 225]]

 [[146 147 143]
  [146 147 143]
  [146 146 146]
  ...
  [240 224 225]
  [239 223 224]
  [238 222 223]]

 ...

 [[135 133 139]
  [135 133 139]
  [131 131

True
[[[151 140 152]
  [149 138 150]
  [155 139 156]
  ...
  [228 225 221]
  [229 225 224]
  [230 226 225]]

 [[151 141 151]
  [151 141 151]
  [153 139 156]
  ...
  [231 225 222]
  [229 225 224]
  [229 225 224]]

 [[150 142 155]
  [149 141 154]
  [153 140 154]
  ...
  [233 224 224]
  [229 225 225]
  [229 225 225]]

 ...

 [[132 136 144]
  [130 134 142]
  [130 134 142]
  ...
  [173 168 172]
  [173 167 173]
  [176 170 176]]

 [[132 136 144]
  [129 133 141]
  [129 132 142]
  ...
  [178 173 177]
  [176 174 175]
  [174 172 173]]

 [[129 133 141]
  [125 129 137]
  [126 129 139]
  ...
  [173 172 176]
  [168 175 174]
  [166 173 172]]]
True
[[[144 142 155]
  [149 147 160]
  [141 145 153]
  ...
  [232 226 232]
  [240 225 231]
  [236 221 227]]

 [[144 142 155]
  [148 146 159]
  [142 147 152]
  ...
  [234 225 232]
  [235 223 228]
  [234 222 227]]

 [[143 143 154]
  [146 146 157]
  [144 146 152]
  ...
  [234 227 229]
  [234 222 227]
  [234 222 227]]

 ...

 [[133 134 138]
  [134 135 139]
  [137 135